# Generated by Django 4.2.3 on 2023-10-11 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=255)),
                ("lastName", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=255)),
                ("distance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("password", models.CharField(max_length=128)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Livreurs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("libre", "Libre"),
                            ("en_cours_de_livraison", "En cours de livraison"),
                        ],
                        default="libre",
                        max_length=50,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="Plats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("plat", "Plat"), ("dessert", "Dessert")],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="plats_images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commandes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateCommande", models.DateTimeField()),
                ("statut", models.CharField(max_length=255)),
                ("numeroCommande", models.CharField(max_length=10, unique=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.clients",
                    ),
                ),
                (
                    "livreur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.livreurs",
                    ),
                ),
                ("plats", models.ManyToManyField(to="backend.plats")),
            ],
        ),
    ]
